[supervisord]
nodaemon=true
logfile=/home/fotas/fotas-ai/aiworks/ailab/start_training/queue/logs/supervisord.log
pidfile=/tmp/supervisord.pid

[program:flask_app]
command=python3 /tf/start_training/queue/app.py
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
autorestart=true

[program:tracker]
command=python3 /tf/start_training/queue/tracker.py
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
autorestart=true

